main: main.agda stlc-main.agda
	agda -i . -i ~/gratr2/agda -i ~/ial -c main.agda

stlc-main: stlc-main.agda
	agda -i . -i ~/gratr2/agda -i ~/ial -c stlc-main.agda

stlc-main.agda: stlc.gr
	gratr stlc.gr